16.0 [2227][MIG] project_task_reply_stage
qrtl/qrtl-custom pull request #24
Opened 2022-11-09 09:44 UTC by AungKoKoLin1997

[2227](https://www.quartile.co/web#id=2227&action=771&model=project.task&view_type=form&menu_id=505)

2022-11-09 14:33 UTC, yostashiro requested changes

2022-11-09 14:33 UTC, yostashiro commented on project_task_reply_stage/models/mail_message.py
> +        for res in messages:
```suggestion
        for message in messages:
```
`res` should be used for returned values/records from a method.  It's weird to use it in the manner you do.

2022-11-09 14:33 UTC, yostashiro commented on project_task_reply_stage/models/mail_message.py
> +                            task.sudo().write({"stage_id": reply_stage.id})
This looks overly cumbersome and inefficient. For example, check on the model and getting reply_stage should be done outside the for loop (I do not think multiple models ever get involved in a create if I'm not mistaken).

Try to reduce the if ladder by getting out of the loop with `continue` when conditions are not met, for example.

2022-11-13 16:17 UTC, AungKoKoLin1997 commented on project_task_reply_stage/models/mail_message.py
> +                            task.sudo().write({"stage_id": reply_stage.id})
I don't think we can check the model outside the for loop.When I reply mail for sale order and project task and then fetch the mail, I got two message in create method with each model.

2022-11-17 14:39 UTC, yostashiro requested changes

2022-11-17 14:39 UTC, yostashiro commented on project_task_reply_stage/models/mail_message.py
> +                    task.sudo().write({"stage_id": reply_stage.id})
```suggestion
            if task.state == "draft":
                continue
            user = message.author_id.user_ids[:1]
            if not (user and user.has_group("base.group_user")):
                continue
            project = task.project_id
            if project and project.customer_reply_stage_id:
                task.sudo().write({"stage_id": project.customer_reply_stage_id.id})
                continue
            reply_stage_id = int(
                self.env["ir.config_parameter"]
                .sudo()
                .get_param("project_task_reply_stage.customer_reply_stage_id")
            )
            if reply_stage_id in project.type_ids.ids:
                task.sudo().write({"stage_id": reply_stage_id})
```
Just made the code concise.  Please confirm that this is valid.

2022-11-17 14:39 UTC, yostashiro commented on project_task_reply_stage/models/mail_message.py
> +# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).
```suggestion
# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl).
```

2022-11-18 04:43 UTC, yostashiro commented
@AungKoKoLin1997 Can you please go ahead and create a PR for project_task_stage_state in qrtl-oca and and fix the CI of this PR?

2022-11-18 04:48 UTC, AungKoKoLin1997 commented
> Can you please go ahead and create a PR for project_task_stage_state in qrtl-oca and and fix the CI of this PR?

@yostashiro I am waiting for this [PR](https://github.com/OCA/project/pull/1009) to be a good state and merged.

2022-11-18 05:57 UTC, yostashiro commented
@AungKoKoLin1997 We do not need to wait for the OCA PR to be merged for this one, IMO.  The possible design change discussed won't affect us.  We do not need to rush to process this PR either, however I'd rather reduce the backlog where going ahead doesn't impose any visible risk.

2022-11-21 02:34 UTC, yostashiro approved these changes

2022-11-21 02:34 UTC, merged